# Generated by Django 4.0.2 on 2024-07-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'AssetLocation',
            },
        ),
        migrations.DeleteModel(
            name='AssetLocation',
        ),
    ]
